# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [41]:
from pprint import pprint

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

In [45]:
# @hidden_cell

# Define API key
weather_api_key = "15cad574d73ac45ca4b3aaf3137621a0"
gkey = "AIzaSyCbZMfCdmn2vJ-gwb39wSFlv4aYjdCHmkQ"

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [16]:
df = pd.read_csv(r"C:\Users\tmkez\Desktop\homework\python-api-challenge\cities.csv")
print(df['Humidity'].max())
df.head()

100.0

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,upernavik,100.0,GL,2020-04-12,88.0,72.79,-56.15,19.87,1.63
1,cherskiy,96.0,RU,2020-04-12,96.0,68.75,161.30,19.17,14.20
2,vanavara,0.0,RU,2020-04-12,90.0,60.34,102.28,30.11,2.26
3,mar del plata,68.0,AR,2020-04-12,82.0,-38.00,-57.56,62.01,4.70
4,albany,1.0,US,2020-04-12,38.0,42.60,-73.97,42.80,9.17

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [17]:
# Configure gmaps
gmaps.configure(api_key=gkey)

locations = df[["Lat", "Lng"]]
humidity = df["Humidity"]

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=humidity, 
                                 dissipating=False, 
                                 max_intensity=300,
                                 point_radius=5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [33]:
hotel_df = df.loc[(df['Max Temp'] > 70) 
                  #& ((df['Country'] == 'US') | (df['Country'] == 'GB') | (df['Country'] == 'CA')) 
                  & (df['Cloudiness'] < 2)
                  & (df['Wind Speed'] < 10) 
                  #& (df['Humidity'] < 15)
                  #& ((df['Cloudiness'] > 5) & (df['Cloudiness'] < 10))
                 ]
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
76,taoudenni,0.0,ML,2020-04-12,12.0,22.68,-3.98,86.47,9.42
78,bidar,0.0,IN,2020-04-12,24.0,17.90,77.55,77.72,7.25
154,srikakulam,0.0,IN,2020-04-12,85.0,18.30,83.90,78.15,5.10
177,ukiah,1.0,US,2020-04-12,49.0,39.15,-123.21,71.60,5.82
232,thinadhoo,0.0,MV,2020-04-12,64.0,0.53,72.93,84.00,5.44
297,marzuq,1.0,YE,2020-04-12,49.0,14.40,46.47,71.33,4.16
316,dakar,1.0,SN,2020-04-12,88.0,14.69,-17.44,75.20,4.70
339,atar,0.0,MR,2020-04-12,20.0,20.52,-13.05,80.98,7.96
489,tura,0.0,IN,2020-04-12,26.0,25.52,90.22,71.02,2.80
491,midland,1.0,US,2020-04-12,16.0,32.00,-102.08,80.60,9.17
530,las vegas,1.0,US,2020-04-12,23.0,36.17,-115.14,75.99,9.17

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [34]:
hotel_df['Hotel Name'] = ""
hotel_df

C:\Users\tmkez\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
76,taoudenni,0.0,ML,2020-04-12,12.0,22.68,-3.98,86.47,9.42,
78,bidar,0.0,IN,2020-04-12,24.0,17.90,77.55,77.72,7.25,
154,srikakulam,0.0,IN,2020-04-12,85.0,18.30,83.90,78.15,5.10,
177,ukiah,1.0,US,2020-04-12,49.0,39.15,-123.21,71.60,5.82,
232,thinadhoo,0.0,MV,2020-04-12,64.0,0.53,72.93,84.00,5.44,
297,marzuq,1.0,YE,2020-04-12,49.0,14.40,46.47,71.33,4.16,
316,dakar,1.0,SN,2020-04-12,88.0,14.69,-17.44,75.20,4.70,
339,atar,0.0,MR,2020-04-12,20.0,20.52,-13.05,80.98,7.96,
489,tura,0.0,IN,2020-04-12,26.0,25.52,90.22,71.02,2.80,
491,midland,1.0,US,2020-04-12,16.0,32.00,-102.08,80.60,9.17,
530,las vegas,1.0,US,2020-04-12,23.0,36.17,-115.14,75.99,9.17,

In [35]:
# params dictionary to update each iteration
params = {
    #"radius": 5000,
    "rankby": "distance",
    #"name": "hotel",
    "type": "lodging",
    "keyword": "hotel",
    "key": gkey
}

for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)

    # convert to json
    name_address = name_address.json()
    #pprint(name_address)
    
    
    results = name_address['results']
    
    try:
        print(f"Closest hotel to {row['City']} is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.
Closest hotel to bidar is Kaveri Hotel.

C:\Users\tmkez\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest hotel to srikakulam is SVA Hotel Grand.
Closest hotel to ukiah is Economy Inn Ukiah.
Closest hotel to thinadhoo is Sunset Stay.
Missing field/result... skipping.
Closest hotel to dakar is Wakola Hotels.
Closest hotel to atar is Oumou Elghoura.
Closest hotel to tura is Hotel RIKMAN Continental.
Closest hotel to midland is DoubleTree by Hilton Hotel Midland Plaza.
Closest hotel to las vegas is Oasis at Gold Spike.

In [36]:
hotel_df = hotel_df.replace("", np.NaN).dropna()
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
78,bidar,0.0,IN,2020-04-12,24.0,17.90,77.55,77.72,7.25,Kaveri Hotel
154,srikakulam,0.0,IN,2020-04-12,85.0,18.30,83.90,78.15,5.10,SVA Hotel Grand
177,ukiah,1.0,US,2020-04-12,49.0,39.15,-123.21,71.60,5.82,Economy Inn Ukiah
232,thinadhoo,0.0,MV,2020-04-12,64.0,0.53,72.93,84.00,5.44,Sunset Stay
316,dakar,1.0,SN,2020-04-12,88.0,14.69,-17.44,75.20,4.70,Wakola Hotels
339,atar,0.0,MR,2020-04-12,20.0,20.52,-13.05,80.98,7.96,Oumou Elghoura
489,tura,0.0,IN,2020-04-12,26.0,25.52,90.22,71.02,2.80,Hotel RIKMAN Continental
491,midland,1.0,US,2020-04-12,16.0,32.00,-102.08,80.60,9.17,DoubleTree by Hilton Hotel Midland Plaza
530,las vegas,1.0,US,2020-04-12,23.0,36.17,-115.14,75.99,9.17,Oasis at Gold Spike

In [37]:
#push to csv using utf-8 encoding

hotel_df.to_csv(r"C:\Users\tmkez\Desktop\homework\python-api-challenge\vacation_hotels.csv", index=False, encoding='utf-8-sig')

In [38]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [39]:
# Configure gmaps
gmaps.configure(api_key=gkey)

locations = df[["Lat", "Lng"]]
humidity = df["Humidity"]

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=humidity, 
                                 dissipating=False, 
                                 max_intensity=200,
                                 point_radius=2)

fig.add_layer(heat_layer)


# Add marker layer ontop of heat map
marker_locations = hotel_df[['Lat', 'Lng']]

markers = gmaps.marker_layer(marker_locations,
    info_box_content=hotel_info)
fig.add_layer(markers)

fig

Figure(layout=FigureLayout(height='420px'))